### ISSUE TITLE
Can't remove friends

### ISSUE THREAD

**Issue by afkgeek** [subliun/Antox#15]
The removing friends functionality within Antox does not remove them permanently.

After logging out and back in again the friend/account that had been removed is displayed again with the ID being used in place of the nickname.

Could it be a case that the information is not being removed from the database correctly?

**Comment by subliun** [comment]
It works for me. Did you do anything special with the friend?

**Comment by afkgeek** [comment]
The only thing that might be special about it is that it was a friend that got copied across when I imported a profile.

I am going to do some further checks later today.

**Comment by afkgeek** [comment]
I have done some various tests and checks.

From what I can tell, if the friend you are trying to remove is part of the imported profile then the friend will be reloaded into the friend list when you next login using the imported profile.

If the friend being deleted is not in the imported profile file then they are removed as expected.

So appears to be an issue with friends included in the profile file.

**Comment by subliun** [comment]
This should be fixed now.

**Comment by afkgeek** [comment]
I have retested and it still isn't removing the friends that come under the imported profile.

When it saves, where is it saving the information to or is it just temporary?

**Comment by subliun** [comment]
It saves to the data file. Try uninstalling and reinstalling and make sure you have the latest build. I tested it and it works for me.

**Comment by subliun** [comment]
I can no longer reproduce this. If it's still an issue for you on the latest build with a newly imported profile I'll reopen.

**Comment by afkgeek** [comment]
I have retested on the latest build and it is now working for me. Thank you :smile_cat:
