### ISSUE TITLE
added tow.im repo to f-droid but can't install antox

### ISSUE THREAD

**Issue by jontis** [subliun/Antox#21]
I've added tox.im repo to f-droid and antox shows up in searches but I'm unable to install it.
It installs fine when I download the .apk.

The phone has an Intel® Atom™ processor Z2560.
If I understand it, the package is for arm architecture? and the phone would require Intel?
However, the downloaded apk installed fine and the app seems to work good.

**Comment by subliun** [comment]
This issue should be fixed now. Please try again with the latest build from F-Droid. Sorry about the delay.

**Comment by jontis** [comment]
I have tried now. It does not work.I think it looks slightly different from before, but I'm still not able to install it.
I'll get you a screenshot if that helps.

**Comment by subliun** [comment]
That would help, thanks. What error message are you getting?

**Comment by jontis** [comment]
None. It just wont install.I can't click to install it.

**Comment by jontis** [comment]
From:
                            
                            subliun <notifications@github.com>;                            
                            
                                To:
                            
                            subliun/Antox <Antox@noreply.github.com>;                                                     
                            
                                Cc:
                            
                            jontis <emailjonathananderson-github@yahoo.com>;                                                     
                            
                                Subject:
                            
                            Re: [Antox] added tow.im repo to f-droid but can't install antox (#21)                            
                            
                                Sent:
                            
                            Fri, Feb 27, 2015 11:33:09 PM                            
                        
                            
                            
                                
                                    
                                        That would help, thanks. What error message are you getting?

—Reply to this email directly or view it on GitHub.

**Comment by louipc** [comment]
Whatever you're doing in email is making your replies really hard to read. Please investigate. Maybe try stripping all of the quoting in replies.

**Comment by jontis** [comment]
![image](https://cloud.githubusercontent.com/assets/1307210/6423333/d3ef619c-bee4-11e4-88a9-29139b6bfff7.png)

**Comment by jontis** [comment]
![image](https://cloud.githubusercontent.com/assets/1307210/6423339/e9fe59d4-bee4-11e4-9a49-feb46afcdfa0.png)

**Comment by jontis** [comment]
I'm looking at adding support for x86 and mips to this apk. Would it be a lot of work for you to build libtoxcore for those too?

**Comment by subliun** [comment]
sonOfRa will hopefully be setting up x86 builds of tox4j this weekend. It should be fairly trivial to make Antox work on x86 then.
